# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_PREFER_SYSTEM_BIN'] = '0'

Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh" // add ubuntu provisioning script here
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  # Kubernetes microk8s node
  config.vm.define "microk8s" do |microk8s|
    microk8s.vm.box = "ubuntu/xenial64"
    microk8s.vm.hostname = "microk8s.example.com"
    microk8s.vm.provider "virtualbox" do |v|
      v.name = "microk8s"
      v.memory = 4096
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    microk8s.vm.provision "shell", path: "bootstrap_microk8s.sh"
  end

end
